### ISSUE TITLE
thanks for Multus-service

### ISSUE THREAD

**Issue by rsidhaarth** [k8snetworkplumbingwg/multus-service#30]
I have not tried multus-service yet. But my requirement as follows

I have a dedicated server setup with dual nic (1Gbits and 10Gbits)

use 10Gbit for all my pods

Why I need 10Gbit? 

a) I want CEPH-ROOK to have faster connection
b) I want mariadb galera to communicate faster in replication

I found that, it is not possible to use 10Gbit as my primary interface in pods other than have it as secondary interface unless I know a lot about CNI

ROOK-CEPH provided an option to use multus network and it make use of it. So requirement A solved

Now, I want to solve B, unless I found a way to use secondary network as primary this cannot be solved, then I am looking for some thing which helps me to use my secondary NIC for service and I found multus-service

now my requirements are met, please believe that, this will help many users to solve complex issue, so please contribute it. If possible add donation link to show support.

**Comment by s1061123** [comment]
Thank you for your feedback to multus-service and happy that multus-service fits your requirements!

Currently this repository is still in prototype to get feedback and gather requirements because several challenge is still in this area:

- integration with load-balancer
- needs to change (or somehow to avoid) Kubernetes implementation (some Kubernetes code of course expects that only one interface in Pod/container and no additional interfaces)

We, network plumbing working group, continue to work on that and find a way for that. Keep in touch!
