### ISSUE TITLE
DPDK Support over multus-service

### ISSUE THREAD

**Issue by Rouf111** [k8snetworkplumbingwg/multus-service#38]
I was trying to add the NAD which makes use of the user-space network (Driver: vfio-pci); however, it doesn't seem to work/support. Are we expecting this to be supported in the near future?

**Comment by s1061123** [comment]
Hi,

- Need to keep in mind that `It is now pretty early stage of development, hence everything may be changed without any notification` as I note in README.md
- Currently multus-service designs to delegate packet forwarding to iptables in mutus-proxy. In DPDK case, as you understand, iptable forwarding is not available because of DPDK design (DPDK does not use linux kernenl network stack). But it does not means multus-service does not suppoprt it. I mean multus-service already provide enough information to create forwarding rule in Kubernetes service API and endpointslice API. Hence DPDK app implements forwarding based on Kubernetes service/endpointslice information, then it could.
